plugins:
  flexible_rate_limits_enabled:
    default: true
    client: true
  flexible_rate_limits_stats:
    default: true
    client: true
  flexible_rate_limits_debug:
    default: true
    client: true
